version: '3.8' 

services:
  website:
    image: wordpress:latest 
    ports:
      - 8083:80
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "aa"  
      WORDPRESS_DB_NAME: wordpress
    restart: always

  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "aa" 
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always

